### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by elliotwutingfeng** [ssddanbrown/Open-Source-Confusion-Cases#19]
Like their parent company [Sentry](https://sentry.io), [Codecov](https://codecov.io) is now licensed under BUSL. However, they claim to be "**now** open source".

**Announcement:** <https://about.codecov.io/blog/codecov-is-now-open-source>
**Hackernews thread (with responses from codecov staff):** <https://news.ycombinator.com/item?id=36971490>

**Comment by ssddanbrown** [comment]
Thanks @elliotwutingfeng, had not seen this!
I'd probably combine this as an entry with #7, since it's the same folks doing the same shifty things.
These combined make it pretty clear-cut they're being misleading with open source.

Another case where they're attempting to act as a "saviour" of open source by "evolving" the term (while better suiting their business interests). Some choice quotes from their employees:

>  The only way for businesses to release their core products under OSI-approved licenses is through a time delay such as the BSL.

> I’ll tell you what’s abusive - people thinking they have the rights to other peoples work unconditionally, or that they can profiteer off it without contributing back. 

> We need to evolve our irrational views of idealism and find common ground that allows sustainability if we want open source to thrive. 

> That seems better to me than the current situation, and if in your view that is a change in the essence of open source, then yes, let's change open source. Change or die. [...] [disclosure: I'm Head of Open Source at Sentry, which owns Codecov.]

**Comment by ssddanbrown** [comment]
A follow up by Sentry due to the reaction of HN:

https://blog.sentry.io/lets-talk-about-open-source/

They double-down on wanting to redefine open source, specifically with this:

> We hope to better define what sustainable open source models can look like, including semi-restrictive licenses like the BUSL. We don’t know what that means quite yet, but we’ll make sure that we share our ideas with the community in the future.

**Comment by elliotwutingfeng** [comment]
Codecov appears to have removed all misleading references to "open source" on the marketing/github repo docs now.

**Comment by illiliti** [comment]
Codecov no longer abuses open-source term for marketing purposes.

> They double-down on wanting to redefine open source, specifically with this:

You can forward your concern to this issue: https://github.com/codecov/feedback/issues/48

**Comment by ssddanbrown** [comment]
Thanks @elliotwutingfeng  and @illiliti.
I've added Codecov as an addressed case: https://github.com/ssddanbrown/Open-Source-Confusion-Cases/blob/main/addressed/codecov.md
I also added sentry as a non-addressed case: https://github.com/ssddanbrown/Open-Source-Confusion-Cases/blob/main/cases/sentry.md
