### ISSUE TITLE
FreeFileSync

### ISSUE THREAD

**Issue by elliotwutingfeng** [ssddanbrown/Open-Source-Confusion-Cases#37]
FreeFileSync is a file synchronization program for Windows/macOS/Linux.

FreeFileSync standard edition is licensed under GPLv3, however, the FAQs state that it is [not for commercial use](https://freefilesync.org/faq.php#commercial), which is an additional restriction not covered by GPLv3 section 7, and hence can be removed by the user.

It appears that the standard edition used to not have such additional restrictions before [version 13](https://freefilesync.org/forum/viewtopic.php?t=10664&hilit=license#p40512).

According to another forum topic, the [Windows source code](https://freefilesync.org/forum/viewtopic.php?t=8644) is also missing from the source code zip available on the [official website](https://freefilesync.org/download.php).

**Comment by ssddanbrown** [comment]
Thanks @elliotwutingfeng,
I've queried the licensing here: https://freefilesync.org/forum/viewtopic.php?t=11016

I'll focus on the license side for this, since the windows bits get a bit more complex to check, and those threads are a couple of years old.

**Comment by elliotwutingfeng** [comment]
No response from the author of FreeFileSync as of today.

**Comment by ssddanbrown** [comment]
Thanks again @elliotwutingfeng,
I've now added this to the repo within 979acdc87ee824fc1d963f9e2fc803fa3c02b8d9.
