### ISSUE TITLE
QuestPDF

### ISSUE THREAD

**Issue by defron** [ssddanbrown/Open-Source-Confusion-Cases#52]
Project: https://github.com/QuestPDF/QuestPDF

Website: https://www.questpdf.com/

### Concerns

- Previously available to all under MIT, they modified the the license in early 2023 to one they made that they call the "QuestPDF License"
- The "QuestPDF License" restricts the usage to groups based on revenue, which violates the Open Source Initiative's Open Source Definition's 5th criteria
- The "QuestPDF License" restricts the usage from fields of endeavor with its "Do No Harm" clause, hich violates the Open Source Initiative's Open Source Definition's 6th criteria
- The website still claims it is under the MIT license in the footer, when it is not.
- Various other concerns with the verbiage of their custom license that causes confusion in various scenarios that are too vague to be relied on and detailed in the below open issue

### Queries

Raised on their own issues board with no reply: https://github.com/QuestPDF/QuestPDF/issues/818

**Comment by richarson** [comment]
Duplicate of https://github.com/ssddanbrown/Open-Source-Confusion-Cases/issues/29?

**Comment by defron** [comment]
I don't know how I missed that and glad to see it's been brought to attention and ready to add. Hopefully the new issue and complete silence on QuestPDF's behalf along with the additional points shows that QuestPDF is willfully not compliant with OSI's Open Source Definition.
