### ISSUE TITLE
Floorp

### ISSUE THREAD

**Issue by ivan-cukic** [ssddanbrown/Open-Source-Confusion-Cases#53]
The Floorp web browser (fork of Firefox) claims that it is open source https://floorp.app/en whereas some parts are only /source available/ - see the license https://github.com/Floorp-Projects/Floorp-private-components/blob/main/LICENSE

"You may not use or distribute this Software or any derivative works in any form for commercial purposes. Examples of commercial purposes would be running business operations, licensing, leasing, or selling the Software, or distributing the Software for use with commercial products."

**Comment by peter-fb** [comment]
It seems that Floorp is open source again: https://www.reddit.com/r/Floorp/comments/1dhxd7f/refullopensourced/

See also here for the changes that were made: https://github.com/Floorp-Projects/Floorp-core/commit/8ae8ee6c443059a045cf7df34b4caaa0d86cea47

**Comment by ivan-cukic** [comment]
Good, we can only hope that the Open Source Confusion Cases helped here ;)

I'll close, and watch closely in the future.
